student/urls.py
from django.contrib import admin
from django.urls import path, include
from website.views import homeview, download_view, productview, subject_view, contact_view, product_upload_view
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    path('admin/', admin.site.urls, name="admin"),
    path('', homeview, name="home"),
    # i have done this to hide main url of set
    path('action/', include("website.urls", namespace="action")),
    path('buy', productview, name="buysell"),
    path('upload', product_upload_view, name="upload"),
    # path('upload', simple_upload, name="upload"),
    path('books', subject_view, name="books"),
    path('paper', subject_view, name="paper"),
    path('contact', contact_view, name="contact"),
    path('books/<str:name>/', download_view, name="books"),
    path('paper/<str:name>/', download_view, name="books"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from website.views import product_filter, product_delete, product_approve, admin_upload_view, notice_upload_view

app_name = "website"
urlpatterns = [

    # path('set', setcontent_view, name="set"),  # insert new record
    path('approve', product_filter, name="filter"),
    # path('download', s3download, name="s3download"),
    path('upload', admin_upload_view, name="adminupload"),
    path('upload/notice', notice_upload_view, name="noticeupload"),
    path('approve/<int:id>/approve', product_approve, name="approve"),
    path('approve/<int:id>/delete', product_delete, name="remove"),

]

templates/Contact.html
{% extends 'templates/base.html' %}
{% load static %}
{% block page %}
<link rel="stylesheet" href="{% static 'static/css/Style-contact.css' %}">
<div class="main">
  <div class="container-profiles">
    <div class="flex">
      <p>CONTACT US</p>
    </div>
    <div class="profile-box">

      <div class="profiles">
        <img
          src="https://scontent-del1-1.xx.fbcdn.net/v/t1.0-9/p720x720/73067827_500712763865726_7544997369897549824_o.jpg?_nc_cat=100&_nc_oc=AQkWg-I5aNdMPuXr2wyUKy-84zhux-b9llZollpR5kUrfnE5R9oSdpcdCPpwv7MBzlQ&_nc_ht=scontent-del1-1.xx&_nc_tp=1002&oh=671192776ee9010fb41cdbc963fd9bd5&oe=5E971DE1">
        <h3>Mohit Pandey<br></h3>
        <h3>CSE</h3><br>


        <div class="contact-details">
          <p class="social mail"><i class="fa fa-envelope"> &nbsp mp0392405@gmail.com</i></p>
          <a href="https://www.facebook.com/profile.php?id=100017810204977" class="social fb"><i
              class="fa fa-facebook-square"></i>mohit
            pandey</a>
          <a href="https://www.instagram.com/_mojo_ji_/" class="social instagram"><i
              class="fa fa-instagram"></i>@mojo_ji</a>
        </div>

      </div>

      <div class="profiles">
        <img
          src="https://scontent.fvns1-1.fna.fbcdn.net/v/t1.0-9/s960x960/82428342_826908247732099_4362870879273615360_o.jpg?_nc_cat=100&_nc_oc=AQn4Re0z3ChuzXgGquY7JV8y2xL9G-2NAXF2HozuoFWigju09hQ4oX_t7FxnXlJil6Y&_nc_ht=scontent.fvns1-1.fna&_nc_tp=1002&oh=63eef8fe2cc3c46a3b1f3a1d01f64882&oe=5ED7F5C0">
        <h3>Ishaan Gupta<br></h3>
        <h3>CSE</h3><br>
        <div class="contact-details">
          <a href="#" class="social mail"><i class="fa fa-envelope"></i>guptaishan849@gmail.com</a>
          <a href="https://www.facebook.com/profile.php?id=100012387941382" class="social fb"><i
              class="fa fa-facebook-square"></i>ishan gupta</a>
          <a href="https://www.instagram.com/ishan_9005/" class="social instagram"><i
              class="fa fa-instagram"></i>@ishan_gupta</a>
        </div>

      </div>
      <div class="profiles">
        <img
          src="https://scontent-del1-1.xx.fbcdn.net/v/t1.0-9/p720x720/72648814_2477572945852096_7370057003969806336_o.jpg?_nc_cat=101&_nc_oc=AQmVcz3CLyaGzWp1jzTtQAhrYhpWJSDVrkf3YiPZVbnMMtLUYhA2LDqPTscPF7ZERTQ&_nc_ht=scontent-del1-1.xx&_nc_tp=1002&oh=39058a84f5b0d6f387c1aa20b5b8968c&oe=5E9BD951">
        <h3>Lovedeep Singh Kamal<br></h3>
        <h3>IT</h3><br>
        <div class="contact-details">
          <p class="social mail"><i class="fa fa-envelope"></i>developer.lovedeep@gmail.com</p>
          <a href="https://www.facebook.com/lovedeep.singhkamal.3" class="social fb"><i
              class="fa fa-facebook-square"></i>lovedeep singh kamal</a>
          <a href="https://www.instagram.com/lovedeep_codes/" class="social instagram"><i
              class="fa fa-instagram"></i>@lovedeep_codes</a>
        </div>
      </div>
    </div>
  </div>
</div>
{%endblock %}

templates/adminupload.html
{% extends 'templates/base.html' %}
{% load static %}
{% block page %}

<link rel="stylesheet" href="{% static 'static/css/style-admin-upload.css' %}">
<title>admin upload page</title>
<div class="container">
    <h1 class="title">upload file</h1>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="entity">
            <label for="file">choose file</label>
            <!-- <input type="file" name="file" id=""> -->
            {{fileuploadform.uploaded_file}}
            {{fileuploadform.uploaded_file.errors}}
        </div>
        <br>
        <div class="entity">
            <label for="filename">filename:</label>
            <!-- <input type="text" name="filename" id="" class="w100"> -->
            {{fileuploadform.name}}
        </div>
        <br>
        <div class="row entity">
            <div class="entity w50">
                <label for="subject">subject:</label>
                <br>
                <!-- <select name="subject" id="" class="w100">
                    
                     

                    {% for subject in subject_list %}
                    <option value="{{subject}}">{{subject}}</option>
                    {% endfor %}
                </select> -->
                {{fileuploadform.subject}}
            </div>
            <div class="entity w50">
                <label for="type">type:</label>
                <br>
                <!-- <select name="type" id="" class="w100">
                    <option value="books and notes">books and notes</option>
                    <option value="paper">paper</option>
                </select> -->
                {{fileuploadform.category}}
            </div>
        </div>
        <br>
        <!-- {{form.name.as_p}} -->
        <p class="url entity">{{url}}</p>
        <button type="submit" value="upload">upload</button>
    </form>
</div>


<!-- form for uploading notice and activity -->
<div class="container">
    <h1 class="title">upload notice and activity</h1>
    <form action="upload/notice" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="entity">
            <label for="file">choose file</label>
            <!-- <input type="file" name="file" id=""> -->
            {{noticeform.uploaded_file}}
            {{noticeform.uploaded_file.errors}}
        </div>
        <br>
        <div class="entity">
            <label for="filename">filename:</label>
            <!-- <input type="text" name="filename" id="" class="w100"> -->
            {{noticeform.name}}
        </div>
        <br>
        <div class=" entity">
            <!-- <div class="entity w50">
                <label for="subject">subject:</label>
                <br>
                <select name="subject" id="" class="w100">
                    
                     

                    {% for subject in subject_list %}
                    <option value="{{subject}}">{{subject}}</option>
                    {% endfor %}
                </select> 
                {{noticeform.subject}}
            </div> -->
            <!-- <div class="entity w50"> -->
            <label for="type">type:</label>
            <br>
            <!-- <select name="type" id="" class="w100">
                    <option value="books and notes">books and notes</option>
                    <option value="paper">paper</option>
                </select> -->
            {{noticeform.category}}
            <!-- </div> -->
        </div>
        <br>
        <!-- {{form.name.as_p}} -->
        <p class="url entity">{{url}}</p>
        <button type="submit" value="upload">upload</button>
    </form>
</div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>study smart</title>
    <link rel="icon" href="https://studysmartbucket.s3.us-east-2.amazonaws.com/static/logo.jpeg" type="image/gif"
        sizes="128x128">
    <!-- <link rel="icon" href="../Logo.svg" sizes="64x64"> -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat|Pridi&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<style>
    main {
        background-color: var(--primary-color);
        padding-top: 15vh;
    }
</style>

<body>
    {% include 'templates/nav.html' %}
    <main>
        {% block page %}

        {% endblock %}
    </main>

</body>

</html>

templates/download.html
{% extends 'templates/base.html' %}
{% load static %}
{% block page %}
<link rel="stylesheet" href="{% static 'static/css/style-book.css' %}">
<div class="container">
    <div class="flex">
        <p class="heading">{{object.0.subject}}</p>
        <!-- <a href="#" class="upload-btn btn" download>upload</a> -->
    </div>
    {% if object %}
    {% for instance in object %}
    <div class="item flex">
        <p class="item-name">{{instance.name}}</p>

        <a href="{{instance.url}}" class="download-btn btn" download><i class="fa fa-download"
                aria-hidden="true">download</i>
        </a>
    </div>
    {% endfor %}
    {% else %}
    <p class="nothing-text">nothing added yet checkout other subjects</p>
    {% endif %}
</div>
{%endblock %}

templates/filter.html
{% extends 'templates/base.html' %}
{% load static %}
{% block page %}

<div class="container white">
    <div class="flex">
        <p class="heading">buy and sell</p>
        <a href="{%url 'buysell' %}" class="sell-btn btn">product page</a>
    </div>
    <div class="marketplace">
        <link rel="stylesheet" href="{% static 'static/css/style-product.css' %}">
        {% for instance in products reversed %}
        <div class="item product">
            <img src="{{instance.imagesrc}}" alt="product image">
            <div class="item-details">
                <p class="item-name">{{instance.itemname}}</p>
                <p class="item-price">rs {{instance.price}}</p>
            </div>

            <div class="seller">
                <div class="seller-container">
                    <p>contact:</p>
                    <p class="seller-name">{{instance.sellername}}</p>
                    <p class="seller-contact">{{instance.contact}}</p>
                </div>
            </div>

            <div class="action" style="display: flex;justify-content: space-evenly;">
                {% if not instance.isapproved %}
                <a href="{% url 'website:approve' instance.id %}" class="btn">approve</a>
                {% endif %}
                <a href="{% url 'website:remove' instance.id %}" class="btn">delete</a>
            </div>
        </div>
        {% endfor %}

    </div>


</div>
{% endblock %}

templates/index.html
{% extends 'templates/base.html' %}
{% load static %}
{% block page %}
<link rel="stylesheet" href="{% static 'static/css/style.css' %}">
<div class=" container">
    <div class="card">
        <p class="heading heading-lg">notice</p>
        <div class="card-content">
            <table>

                {% for instance in notice %}
                <tr>
                    <td><a href="{{instance.src}}">{{instance.name}}</a></td>
                    <td>{{instance.date}}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>

</div>

<div class="container container-flex">
    <div class="card flex-card">
        <p class="heading">activity</p>
        <div class="card-content">
            <table>

                {% for instance in activity %}
                <tr>
                    <td><a href="{{instance.src}}">{{instance.name}}</a></td>

                </tr>
                {% endfor %}
            </table>
        </div>
    </div>

    <div class="card flex-card">
        <p class="heading">resources</p>
        <div class="card-content">
            <a href="{% url 'books' %}" class="resource-link">books and notes</a>
            <a href="{% url 'paper' %}" class="resource-link">previous year papers</a>
            <a href="{% url 'buysell' %}" class="resource-link">buy and sell</a>
        </div>
    </div>
</div>

<div class="container">
    <div class="card">
        <p class="heading">recently added</p>
        <div class="card-content horizontal">
            <link rel="stylesheet" href="{% static 'static/css/style-product.css' %}">
            {% for instance in products reversed %}
            {% include 'templates/item.html' %}
            {% endfor %}
            {% if products|length > 3 %}
            <a href="{% url 'buysell' %}">
                <div class="product view-more">
                    <p>view <br> more</p>
                </div>
            </a>
            {% endif %}


        </div>
    </div>
</div>
<div class="container">
    <div class="card">
        <p class="heading">tell us</p>
        <div class="card-content">
            <p class="form-text">
                feeling something missing?
            </p>
            <p class="form-subtext">
                let us know
            </p>
            <form action="" method="post">
                {% csrf_token %}
                <input type="text" name="userinput" id="userinput" required>
                <button type="submit">send</button>
            </form>


        </div>
    </div>
</div>

{% endblock %}

templates/item.html
{% if instance.isapproved %}
<div class="item product">
    <img src="{{instance.imagesrc}}" alt="product image">
    <div class="item-details">
        <p class="item-name">{{instance.itemname}}</p>
        <p class="item-price">rs {{instance.price}}</p>
    </div>

    <div class="seller">
        <div class="seller-container">
            <p>contact:</p>
            <p class="seller-name">{{instance.sellername}}</p>
            <p class="seller-contact">{{instance.contact}}</p>
        </div>
    </div>
</div>
{% endif %}

templates/nav.html
{% load static %}
<link rel="stylesheet" href="{% static 'static/css/style-nav.css' %}">
<nav>
    <span class="ham " onclick="openNav()">
        <svg width="35" height="35" viewBox="0 0 24 24" focusable="false" class=" NMm5M">
            <path d="M3 18h18v-2H3v2zm0-5h18v-2H3v2zm0-7v2h18V6H3z">

            </path>
        </svg>
    </span>



    <p class="logo center-hv">study <br> smart</p>

</nav>
<div class="nav-overlay">
</div>

<div class="navbar" id="nav">
    <a href="{%url 'home' %}" class="nav-link">home</a>
    <a href="{%url 'books' %}" class="nav-link">books and notes</a>
    <a href="{%url 'buysell' %}" class="nav-link">buy and sell</a>
    <a href="{% url 'paper' %}" class="nav-link">previous year paper</a>
    <a href="{% url 'contact' %}" class="nav-link">contact us</a>
</div>

<script>
    function openNav() {

        document.getElementById("nav").classList.toggle("openclose")
        document.querySelector(".nav-overlay").classList.toggle("openclose")

        if (screen.width < 750) {
            if (document.querySelector("body").style.overflow == "hidden")
                document.querySelector("body").style.overflow = "auto"
            else
                document.querySelector("body").style.overflow = "hidden"
        }

        // document.querySelector("body").overflow = "hidden"
    }
</script>

templates/product.html
{% extends 'templates/base.html' %}
{% load static %}
{% block page %}

<div class="container white">
    <div class="flex">
        <p class="heading">buy and sell</p>
        <a href="{%url 'upload' %}" class="sell-btn btn">sell</a>
    </div>
    <div class="marketplace">
        <link rel="stylesheet" href="{% static 'static/css/style-product.css' %}">
        {% if products %}
        {% for instance in products reversed %}
        {% include 'templates/item.html' %}
        {% endfor %}
        {% else %}

        <p class="nothing-text">no product to show.<br>click <a href="{%url 'upload' %}">sell</a>
            button to starting selling items</p>
        {% endif %}
    </div>


</div>
{% endblock %}

templates/subject.html
{% extends 'templates/base.html' %}
{% load static %}
{% block page %}
<link rel="stylesheet" href="{% static 'static/css/style-subject.css' %}">
<div class="container">
    <div class="flex">
        <p class="heading">{{pagename}}</p>
    </div>
    <div class="subject-container flex">
        {% for instance in objects %}
        <a href="{{pageurl}}/{{instance.name}}" class="subject">{{instance.name}}</a>
        {% endfor %}
    </div>
</div>
{%endblock %}

templates/upload.html
{% extends 'templates/base.html' %}
{% load static %}
{% block page %}

<link rel="stylesheet" href="{% static 'static/css/style-upload.css' %}">
<div class="container">
    <h1 class="title">sell item</h1>


    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="itemname">product name:</label><br>
        <!-- <input type="text" name="itemname" id="" class="full" required> -->
        {{form.itemname.errors}}
        {{form.itemname}}
        <br>
        <div class="flex">
            <div class="price half">
                <label for="price">price:</label><br>
                <!-- <input type="number" name="price" id="" min="0" class="full" required> -->
                {{form.price}}
                <br>
            </div>
            <div class="image half">
                <label for="myfile">upload image:</label><br>
                <!-- <input type="file" name="myfile" class="full" required> -->
                {{form.uploaded_file.errors}}
                {{form.uploaded_file}}
                <br>
            </div>
        </div>
        <label for="sellername">sellername:</label><br>
        <!-- <input type="text" name="sellername" id="full" class="full" required> -->
        {{form.sellername}}
        <br>
        <label for="contact">contact:</label><br>
        <!-- <input pattern="[1-9]{1}[0-9]{9}" type="number" name='contact' />  -->
        {{form.contact.errors}}
        {{form.contact}}

        <button type="submit" onclick="submitForm()" class="upload">Upload</button>
    </form>
</div>
<script>
    function submitForm() {
        alert(
            'your product is sent for approval !\nyou will be able to see your product once it is approved'
        )

    }
</script>
{% endblock %}